/**
 * This file was auto-generated by openapi-typescript from dogs-openapi.json.
 * Do not make direct changes to the file. Regenerate with:
 *   npx openapi-typescript src/types/dogs-openapi.json -o src/types/dogs.ts
 *
 * These are the canonical DOGS shared-data-model shapes. Frontline does not call the
 * live DOGS API — these types exist purely as the shape contract that Frontline's own
 * Supabase schema / database.ts types are hand-aligned against (see database.ts).
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Directory */
        get: operations["list_directory_directory_get"];
        put?: never;
        /** Create Directory Entry */
        post: operations["create_directory_entry_directory_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/directory/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Directory Entry */
        get: operations["get_directory_entry_directory__entry_id__get"];
        put?: never;
        post?: never;
        /** Delete Directory Entry */
        delete: operations["delete_directory_entry_directory__entry_id__delete"];
        options?: never;
        head?: never;
        /** Update Directory Entry */
        patch: operations["update_directory_entry_directory__entry_id__patch"];
        trace?: never;
    };
    "/cleanups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cleanups */
        get: operations["list_cleanups_cleanups_get"];
        put?: never;
        /** Create Cleanup */
        post: operations["create_cleanup_cleanups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cleanups/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cleanup */
        get: operations["get_cleanup_cleanups__entry_id__get"];
        put?: never;
        post?: never;
        /** Delete Cleanup */
        delete: operations["delete_cleanup_cleanups__entry_id__delete"];
        options?: never;
        head?: never;
        /** Update Cleanup */
        patch: operations["update_cleanup_cleanups__entry_id__patch"];
        trace?: never;
    };
    "/trash-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trash Reports */
        get: operations["list_trash_reports_trash_reports_get"];
        put?: never;
        /** Create Trash Report */
        post: operations["create_trash_report_trash_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trash-reports/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trash Report */
        get: operations["get_trash_report_trash_reports__entry_id__get"];
        put?: never;
        post?: never;
        /** Delete Trash Report */
        delete: operations["delete_trash_report_trash_reports__entry_id__delete"];
        options?: never;
        head?: never;
        /** Update Trash Report */
        patch: operations["update_trash_report_trash_reports__entry_id__patch"];
        trace?: never;
    };
    "/admin/sync-from-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync From Sheet
         * @description Pull Directory of Good rows from Google Sheet, upsert, then geocode missing coordinates.
         */
        post: operations["sync_from_sheet_admin_sync_from_sheet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/erd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Erd
         * @description Mermaid ER diagram (erDiagram) of the live schema — paste into mermaid.live to render.
         */
        get: operations["get_erd_erd_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityStatus
         * @description Shared lifecycle status for cleanups and trash reports.
         * @enum {string}
         */
        ActivityStatus: "open" | "scheduled" | "in_progress" | "completed" | "addressed" | "verified" | "cancelled";
        /** Category */
        Category: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            slug: components["schemas"]["CategorySlug"];
            /** Name */
            name: string;
        };
        /**
         * CategorySlug
         * @enum {string}
         */
        CategorySlug: "animals" | "environment" | "fitness" | "nature" | "trash" | "water";
        /** Cleanup */
        Cleanup: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            location?: components["schemas"]["StructuredLocation"] | null;
            coordinates?: components["schemas"]["Coordinates"] | null;
            /** Scheduled Start */
            scheduled_start?: string | null;
            /** Scheduled End */
            scheduled_end?: string | null;
            status?: components["schemas"]["ActivityStatus"] | null;
            /** Photo Urls */
            photo_urls?: string[];
            metrics?: components["schemas"]["CleanupMetrics"] | null;
            /** Submitted By User Id */
            submitted_by_user_id?: string | null;
            /** Organizer User Ids */
            organizer_user_ids?: string[];
            /** Rsvp User Ids */
            rsvp_user_ids?: string[];
            /** Attended User Ids */
            attended_user_ids?: string[];
        };
        /** CleanupCreate */
        CleanupCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            location?: components["schemas"]["StructuredLocation"] | null;
            /** Scheduled Start */
            scheduled_start?: string | null;
            /** Scheduled End */
            scheduled_end?: string | null;
            status?: components["schemas"]["ActivityStatus"] | null;
            /** Photo Urls */
            photo_urls?: string[];
            metrics?: components["schemas"]["CleanupMetrics"] | null;
            /** Submitted By User Id */
            submitted_by_user_id?: string | null;
            /** Organizer User Ids */
            organizer_user_ids?: string[];
            /** Rsvp User Ids */
            rsvp_user_ids?: string[];
            /** Attended User Ids */
            attended_user_ids?: string[];
        };
        /** CleanupMetrics */
        CleanupMetrics: {
            /** Small Bags */
            small_bags?: number | null;
            /** Large Bags */
            large_bags?: number | null;
            /** Pounds */
            pounds?: number | null;
        };
        /** CleanupUpdate */
        CleanupUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            location?: components["schemas"]["StructuredLocation"] | null;
            /** Scheduled Start */
            scheduled_start?: string | null;
            /** Scheduled End */
            scheduled_end?: string | null;
            status?: components["schemas"]["ActivityStatus"] | null;
            /** Photo Urls */
            photo_urls?: string[] | null;
            metrics?: components["schemas"]["CleanupMetrics"] | null;
            /** Submitted By User Id */
            submitted_by_user_id?: string | null;
            /** Organizer User Ids */
            organizer_user_ids?: string[] | null;
            /** Rsvp User Ids */
            rsvp_user_ids?: string[] | null;
            /** Attended User Ids */
            attended_user_ids?: string[] | null;
        };
        /** Coordinates */
        Coordinates: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** DirectoryEntry */
        DirectoryEntry: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Image Url */
            image_url?: string | null;
            location?: components["schemas"]["StructuredLocation"] | null;
            coordinates?: components["schemas"]["Coordinates"] | null;
            social_links?: components["schemas"]["SocialLinks"] | null;
            /** Categories */
            categories?: components["schemas"]["CategorySlug"][];
            /**
             * Featured
             * @default false
             */
            featured: boolean;
            /** User Ids */
            user_ids?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DirectoryEntryCreate */
        DirectoryEntryCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Image Url */
            image_url?: string | null;
            location?: components["schemas"]["StructuredLocation"] | null;
            social_links?: components["schemas"]["SocialLinks"] | null;
            /** Categories */
            categories?: components["schemas"]["CategorySlug"][];
            /**
             * Featured
             * @default false
             */
            featured: boolean;
            /** User Ids */
            user_ids?: string[];
        };
        /** DirectoryEntryUpdate */
        DirectoryEntryUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Image Url */
            image_url?: string | null;
            location?: components["schemas"]["StructuredLocation"] | null;
            social_links?: components["schemas"]["SocialLinks"] | null;
            /** Categories */
            categories?: components["schemas"]["CategorySlug"][] | null;
            /** Featured */
            featured?: boolean | null;
            /** User Ids */
            user_ids?: string[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SheetSyncResponse */
        SheetSyncResponse: {
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Skipped */
            skipped: number;
            /** Rows Seen */
            rows_seen: number;
            /** Geocoded */
            geocoded: number;
            /** Geo Failed */
            geo_failed: number;
            /** Images Skipped */
            images_skipped: number;
            /** Errors */
            errors: string[];
        };
        /** SocialLinks */
        SocialLinks: {
            /** Website */
            website?: string | null;
            /** Instagram */
            instagram?: string | null;
            /** Tiktok */
            tiktok?: string | null;
            /** Youtube */
            youtube?: string | null;
            /** Facebook */
            facebook?: string | null;
            /** Twitter */
            twitter?: string | null;
        };
        /** StructuredLocation */
        StructuredLocation: {
            /** City */
            city?: string | null;
            /** State */
            state?: string | null;
            /** Zip Code */
            zip_code?: string | null;
            /** Country */
            country?: string | null;
        };
        /** TrashReport */
        TrashReport: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            location?: components["schemas"]["StructuredLocation"] | null;
            coordinates?: components["schemas"]["Coordinates"] | null;
            /** Image Urls */
            image_urls?: string[];
            severity?: components["schemas"]["TrashReportSeverity"] | null;
            status?: components["schemas"]["ActivityStatus"] | null;
            /** Reported At */
            reported_at?: string | null;
            /** Submitted By User Id */
            submitted_by_user_id?: string | null;
            /** Resolved By User Id */
            resolved_by_user_id?: string | null;
            /** Resolved By Cleanup Id */
            resolved_by_cleanup_id?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
        };
        /** TrashReportCreate */
        TrashReportCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            location?: components["schemas"]["StructuredLocation"] | null;
            /** Image Urls */
            image_urls?: string[];
            severity?: components["schemas"]["TrashReportSeverity"] | null;
            status?: components["schemas"]["ActivityStatus"] | null;
            /** Reported At */
            reported_at?: string | null;
            /** Submitted By User Id */
            submitted_by_user_id?: string | null;
        };
        /**
         * TrashReportSeverity
         * @enum {string}
         */
        TrashReportSeverity: "low" | "medium" | "high";
        /** TrashReportUpdate */
        TrashReportUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            location?: components["schemas"]["StructuredLocation"] | null;
            /** Image Urls */
            image_urls?: string[] | null;
            severity?: components["schemas"]["TrashReportSeverity"] | null;
            status?: components["schemas"]["ActivityStatus"] | null;
            /** Reported At */
            reported_at?: string | null;
            /** Submitted By User Id */
            submitted_by_user_id?: string | null;
            /** Resolved By User Id */
            resolved_by_user_id?: string | null;
            /** Resolved By Cleanup Id */
            resolved_by_cleanup_id?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;

// Convenience aliases for the canonical DOGS model shapes.
export type DirectoryEntry = components["schemas"]["DirectoryEntry"];
export type Cleanup = components["schemas"]["Cleanup"];
export type CleanupMetrics = components["schemas"]["CleanupMetrics"];
export type TrashReport = components["schemas"]["TrashReport"];
export type TrashReportSeverity = components["schemas"]["TrashReportSeverity"];
export type ActivityStatus = components["schemas"]["ActivityStatus"];
export type Category = components["schemas"]["Category"];
export type CategorySlug = components["schemas"]["CategorySlug"];
export type Coordinates = components["schemas"]["Coordinates"];
export type StructuredLocation = components["schemas"]["StructuredLocation"];
export type SocialLinks = components["schemas"]["SocialLinks"];
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_categories_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    list_directory_directory_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                category?: components["schemas"]["CategorySlug"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_directory_entry_directory_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectoryEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_directory_entry_directory__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_directory_entry_directory__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_directory_entry_directory__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectoryEntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cleanups_cleanups_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cleanup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_cleanup_cleanups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cleanup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cleanup_cleanups__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cleanup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_cleanup_cleanups__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_cleanup_cleanups__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanupUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cleanup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trash_reports_trash_reports_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashReport"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_trash_report_trash_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrashReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trash_report_trash_reports__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trash_report_trash_reports__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trash_report_trash_reports__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrashReportUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_from_sheet_admin_sync_from_sheet_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetSyncResponse"];
                };
            };
        };
    };
    get_erd_erd_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
